<a href="https://colab.research.google.com/github/sinsun030508/ai/blob/main/%ED%94%BC%EC%A7%80%EC%BB%AC_ai_6%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
X_trin, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()
model.fit(X_trin, y_train)
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print(f"모델의 정확도 : {accuracy*100}%")

모델의 정확도 : 100.0%


In [12]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

x = np.arange(10).reshape(-1,1)
y = np.array([0,1,0,0,1,1,1,1,1,1])

model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score = model.score(x,y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

print(p_pred)
print(y_pred)
print(score)
print(conf_m)
print(report)


[[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
[0 0 0 1 1 1 1 1 1 1]
0.8
[[2 1]
 [1 6]]
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



In [13]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
training_point=[[0.5,0.2,0.1], [0.9,0.7,0.3], [0.4,0.5,0.7]]
training_labels=[0,1,1]

clf.fit(training_point, training_labels)
unknown_point = [[0.2,0.1,0.7], [0.4,0.7,0.6], [0.5,0.8,0.1]]

pred = clf.predict(unknown_point)
print(pred)


[1 1 1]


In [17]:
from sklearn.svm import SVC

classifier = SVC(kernel = 'linear')
training_point = [[1,2], [1,5], [2,2], [7,5], [9,4], [8,2]]
labels = [1,1,1,0,0,0]
classifier.fit(training_point, labels)
print(classifier.predict([[3,2]]))

[1]


In [20]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

iris = load_iris()
df = pd.DataFrame(data=np.c_[iris.data, iris.target],
                  columns=['sepal lenght', 'sepal width', 'petal length', 'petal width', 'target'])
df.head()

,sepal lenght,sepal width,petal length,petal width,target
0,5.1,3.5,1.4,0.2,0.0
1,4.9,3.0,1.4,0.2,0.0
2,4.7,3.2,1.3,0.2,0.0
3,4.6,3.1,1.5,0.2,0.0
4,5.0,3.6,1.4,0.2,0.0


In [22]:
from sklearn.model_selection import train_test_split
X = df[df.columns[:-1]]
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=123)

In [25]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

model = SVC(kernel='poly', C=3, degree=3)
model.fit(X_train, y_train)

SVC(C=3, kernel='poly')

In [30]:
from sklearn.metrics import accuracy_score
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
